# Generated by Django 3.2.16 on 2022-12-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='使用者名稱')),
                ('subject', models.CharField(max_length=50, verbose_name='內容主旨')),
                ('content', models.TextField(verbose_name='內容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
        ),
    ]
